#!/usr/bin/env bash
# =============================================================================
# ONDC Platform — One-Command Deploy
# =============================================================================
# Takes a blank Ubuntu 22.04+ VM to a fully running ONDC network.
# Clone from GitHub, install everything, configure, start.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/divyamohan1993/ondc-network-beckn/main/deploy.sh | bash -s -- --domain ondc.example.com
#
# Or after cloning:
#   ./deploy.sh --domain ondc.example.com
#
# Flags:
#   --domain <domain>     Required. Your domain name.
#   --datagovin <key>     data.gov.in API key for pincode seeding.
#   --skip-seed           Skip pincode database seeding.
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
log() { echo -e "${BLUE}[ONDC]${NC} $1"; }
ok()  { echo -e "${GREEN}[ONDC]${NC} $1"; }
err() { echo -e "${RED}[ONDC]${NC} $1"; }

# ---------------------------------------------------------------------------
# Parse flags
# ---------------------------------------------------------------------------
DOMAIN=""
DATAGOVIN_KEY=""
SKIP_SEED=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain)     DOMAIN="$2"; shift 2;;
    --datagovin)  DATAGOVIN_KEY="$2"; shift 2;;
    --skip-seed)  SKIP_SEED=true; shift;;
    *)            err "Unknown flag: $1"; exit 1;;
  esac
done

if [ -z "$DOMAIN" ]; then
  err "Usage: ./deploy.sh --domain your-domain.com"
  exit 1
fi

log "Deploying ONDC platform on domain: ${BOLD}$DOMAIN${NC}"

# ---------------------------------------------------------------------------
# 1. Install system dependencies
# ---------------------------------------------------------------------------
log "Installing system dependencies..."
sudo apt-get update -qq
sudo apt-get install -y -qq curl git nginx postgresql redis-server rabbitmq-server openssl 2>&1 | tail -3

# Node.js 22
if ! command -v node &>/dev/null || [ "$(node -v | cut -d. -f1 | tr -d v)" -lt 22 ]; then
  log "Installing Node.js 22..."
  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  sudo apt-get install -y -qq nodejs 2>&1 | tail -1
fi

# pnpm + PM2
sudo npm install -g pnpm@10.30.1 pm2 2>&1 | tail -1
ok "System dependencies installed"

# ---------------------------------------------------------------------------
# 2. Clone repo (if not already in one)
# ---------------------------------------------------------------------------
DEPLOY_DIR="$HOME/ondc-network-beckn"
if [ -f "package.json" ] && grep -q "ondc-network-beckn" package.json 2>/dev/null; then
  DEPLOY_DIR="$(pwd)"
  log "Already in project directory: $DEPLOY_DIR"
else
  if [ -d "$DEPLOY_DIR" ]; then
    log "Updating existing clone..."
    cd "$DEPLOY_DIR"
    git pull origin main 2>&1 | tail -3
  else
    log "Cloning repository..."
    git clone https://github.com/divyamohan1993/ondc-network-beckn.git "$DEPLOY_DIR"
    cd "$DEPLOY_DIR"
  fi
fi
cd "$DEPLOY_DIR"
ok "Repository ready at $DEPLOY_DIR"

# ---------------------------------------------------------------------------
# 3. Generate secrets and .env
# ---------------------------------------------------------------------------
log "Generating configuration..."

generate_secret() { openssl rand -base64 "$1" | tr -d '=/+' | head -c "$1"; }
generate_hex()    { openssl rand -hex "$1"; }

POSTGRES_PASSWORD=$(generate_secret 30)
REDIS_PASSWORD=""  # Local Redis, no auth needed
RABBITMQ_PASSWORD=$(generate_secret 30)
VAULT_MASTER_KEY=$(generate_hex 32)
VAULT_TOKEN_SECRET=$(generate_hex 32)
VAULT_API_KEY=$(generate_hex 32)
ADMIN_TOKEN=$(generate_hex 32)
INTERNAL_API_KEY=$(generate_hex 32)
NEXTAUTH_SECRET=$(generate_hex 32)
ADMIN_PASSWORD=$(generate_secret 20)
PII_ENCRYPTION_KEY=$(generate_hex 32)

# Generate Ed25519 signing keys for each service
generate_ed25519() {
  node -e "
    const { ed25519 } = require('@noble/curves/ed25519');
    const pk = ed25519.utils.randomSecretKey();
    const pub = ed25519.getPublicKey(pk);
    console.log(Buffer.from(pk).toString('base64'));
    console.log(Buffer.from(pub).toString('base64'));
  " 2>/dev/null || echo -e "placeholder-key\nplaceholder-pub"
}

# Write .env
cat > .env << ENVFILE
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DOMAIN=$DOMAIN
NODE_ENV=production

# PostgreSQL
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=ondc
POSTGRES_USER=ondc_admin
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgresql://ondc_admin:${POSTGRES_PASSWORD}@localhost:5432/ondc

# Redis
REDIS_URL=redis://localhost:6379

# RabbitMQ
RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
RABBITMQ_URL=amqp://ondc:${RABBITMQ_PASSWORD}@localhost:5672

# Service Ports
REGISTRY_PORT=3001
GATEWAY_PORT=3002
BAP_PORT=3003
BPP_PORT=3004
VAULT_PORT=3006
HEALTH_MONITOR_PORT=3007

# Subscriber IDs
REGISTRY_SUBSCRIBER_ID=registry.$DOMAIN
GATEWAY_SUBSCRIBER_ID=gateway.$DOMAIN
BAP_ID=bap.$DOMAIN
BAP_URI=https://$DOMAIN/api/bap
BPP_ID=bpp.$DOMAIN
BPP_URI=https://$DOMAIN/api/bpp

# Signing Keys (generated)
REGISTRY_SIGNING_PRIVATE_KEY=$(generate_secret 44)
REGISTRY_SIGNING_PUBLIC_KEY=$(generate_secret 44)
GATEWAY_SIGNING_PRIVATE_KEY=$(generate_secret 44)
GATEWAY_SIGNING_PUBLIC_KEY=$(generate_secret 44)
BAP_PRIVATE_KEY=$(generate_secret 44)
BAP_PUBLIC_KEY=$(generate_secret 44)
BAP_UNIQUE_KEY_ID=key-$(generate_hex 4)
BPP_PRIVATE_KEY=$(generate_secret 44)
BPP_PUBLIC_KEY=$(generate_secret 44)
BPP_UNIQUE_KEY_ID=key-$(generate_hex 4)

# Vault
VAULT_MASTER_KEY=$VAULT_MASTER_KEY
VAULT_TOKEN_SECRET=$VAULT_TOKEN_SECRET
VAULT_API_KEY=$VAULT_API_KEY
PII_ENCRYPTION_KEY=$PII_ENCRYPTION_KEY

# Admin
ADMIN_EMAIL=admin@$DOMAIN
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_NAME=admin
ADMIN_TOKEN=$ADMIN_TOKEN
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
NEXTAUTH_URL=https://$DOMAIN/admin

# Internal
INTERNAL_API_KEY=$INTERNAL_API_KEY
LOG_LEVEL=info
CORS_ALLOWED_ORIGINS=https://$DOMAIN

# Payment (mock for demo)
PAYMENT_GATEWAY=mock
SMS_PROVIDER=mock

# Health Monitor
HEALTH_CHECK_URLS=Registry=http://localhost:3001,Gateway=http://localhost:3002,BAP=http://localhost:3003,BPP=http://localhost:3004,Vault=http://localhost:3006
RESPONSE_THRESHOLD_MS=5000
CHECK_INTERVAL_MS=30000

# Data
DATAGOVIN=${DATAGOVIN_KEY}

# DB Pool
DB_POOL_MAX=20
DB_POOL_IDLE_TIMEOUT=30000
DB_POOL_CONNECTION_TIMEOUT=5000
ENVFILE

ok "Configuration generated"

# ---------------------------------------------------------------------------
# 4. Setup PostgreSQL
# ---------------------------------------------------------------------------
log "Setting up PostgreSQL..."
sudo -u postgres psql -c "CREATE USER ondc_admin WITH PASSWORD '$POSTGRES_PASSWORD';" 2>/dev/null || true
sudo -u postgres psql -c "CREATE DATABASE ondc OWNER ondc_admin;" 2>/dev/null || true
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ondc TO ondc_admin;" 2>/dev/null || true
sudo -u postgres psql -d ondc -f db/init.sql 2>&1 | tail -3
sudo -u postgres psql -d ondc -c "GRANT ALL ON ALL TABLES IN SCHEMA public TO ondc_admin;" 2>/dev/null
sudo -u postgres psql -d ondc -c "GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ondc_admin;" 2>/dev/null
ok "PostgreSQL ready"

# ---------------------------------------------------------------------------
# 5. Setup RabbitMQ
# ---------------------------------------------------------------------------
log "Setting up RabbitMQ..."
sudo rabbitmqctl add_user ondc "$RABBITMQ_PASSWORD" 2>/dev/null || true
sudo rabbitmqctl set_permissions ondc ".*" ".*" ".*" 2>/dev/null || true
ok "RabbitMQ ready"

# ---------------------------------------------------------------------------
# 6. Install dependencies and build
# ---------------------------------------------------------------------------
log "Installing npm dependencies..."
pnpm install 2>&1 | tail -3

log "Building all packages (this takes 2-4 minutes)..."
pnpm turbo build 2>&1 | tail -3
ok "Build complete"

# ---------------------------------------------------------------------------
# 7. Configure nginx
# ---------------------------------------------------------------------------
log "Configuring nginx..."
sudo tee /etc/nginx/sites-available/ondc > /dev/null << NGINX
server {
    listen 80;
    server_name $DOMAIN _;
    client_max_body_size 20m;

    # Landing page (docs app serves /)
    location / {
        proxy_pass http://127.0.0.1:3015;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Buyer app at /shop
    location /shop/ {
        proxy_pass http://127.0.0.1:3012/;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
    location = /shop { return 301 /shop/; }
    location /shop/_next/ { proxy_pass http://127.0.0.1:3012/_next/; proxy_set_header Host \$host; }

    # Seller dashboard
    location /seller/ {
        proxy_pass http://127.0.0.1:3013/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
    location = /seller { return 301 /seller/; }
    location /seller/_next/ { proxy_pass http://127.0.0.1:3013/_next/; proxy_set_header Host \$host; }

    # Admin panel
    location /admin/ {
        proxy_pass http://127.0.0.1:3014/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
    location = /admin { return 301 /admin/; }
    location /admin/_next/ { proxy_pass http://127.0.0.1:3014/_next/; proxy_set_header Host \$host; }

    # Docs + Pitch (served by docs app, already handled by / catch-all, but explicit for _next)
    location /pitch { proxy_pass http://127.0.0.1:3015/pitch; proxy_set_header Host \$host; proxy_set_header X-Forwarded-Proto \$scheme; }
    location /docs  { proxy_pass http://127.0.0.1:3015/docs;  proxy_set_header Host \$host; }

    # Auth -> BAP
    location /auth/ { proxy_pass http://127.0.0.1:3003/auth/; proxy_set_header Host \$host; }

    # Registry API
    location /registry/ { proxy_pass http://127.0.0.1:3001/; proxy_set_header Host \$host; }

    # Gateway API
    location /gateway/ { proxy_pass http://127.0.0.1:3002/; proxy_set_header Host \$host; }

    # BAP API
    location /api/bap/ { proxy_pass http://127.0.0.1:3003/; proxy_set_header Host \$host; }

    # BPP API
    location /api/bpp/ { proxy_pass http://127.0.0.1:3004/; proxy_set_header Host \$host; }
}
NGINX

sudo ln -sf /etc/nginx/sites-available/ondc /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t && sudo systemctl reload nginx
ok "nginx configured"

# ---------------------------------------------------------------------------
# 8. Start services with PM2
# ---------------------------------------------------------------------------
log "Starting services..."

# Source env for PM2
set -a && source .env && set +a
export DATABASE_URL REDIS_URL RABBITMQ_URL

# Stop any existing PM2 processes
pm2 kill 2>/dev/null || true

# Start backend services
pm2 start dist/server.js --name registry --cwd packages/registry -- 2>/dev/null
pm2 start dist/server.js --name gateway  --cwd packages/gateway  -- 2>/dev/null
pm2 start dist/server.js --name bap      --cwd packages/bap      -- 2>/dev/null
pm2 start dist/server.js --name bpp      --cwd packages/bpp      -- 2>/dev/null
pm2 start dist/server.js --name vault    --cwd packages/vault    -- 2>/dev/null
pm2 start dist/server.js --name health-monitor --cwd packages/health-monitor -- 2>/dev/null

# Start frontend apps
pm2 start "npx next start -p 3012" --name buyer-app  --cwd packages/buyer-app
pm2 start "npx next start -p 3013" --name seller-app --cwd packages/seller-app
pm2 start "npx next start -p 3014" --name admin      --cwd packages/admin
pm2 start "npx next start -p 3015" --name docs       --cwd packages/docs

# Save and enable auto-start
pm2 save
sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u "$USER" --hp "$HOME" 2>/dev/null || true

ok "All services started"

# ---------------------------------------------------------------------------
# 9. Seed pincode data (optional)
# ---------------------------------------------------------------------------
if [ "$SKIP_SEED" = false ] && [ -n "$DATAGOVIN_KEY" ]; then
  log "Seeding India pincode database from data.gov.in..."
  npx tsx scripts/src/seed-pincodes.ts 2>&1 | tail -3
  ok "Pincodes seeded"
fi

# ---------------------------------------------------------------------------
# 10. Wait for services and verify
# ---------------------------------------------------------------------------
log "Waiting for services to start..."
sleep 15

echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  ONDC Platform Deployed Successfully${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo ""

PASS=0; FAIL=0
for pair in \
  "Buyer App|http://localhost:3012" \
  "Seller Dashboard|http://localhost:3013" \
  "Admin Panel|http://localhost:3014" \
  "Registry|http://localhost:3001/health" \
  "Gateway|http://localhost:3002/health" \
  "BAP|http://localhost:3003/health" \
  "BPP|http://localhost:3004/health"; do
  IFS="|" read -r name url <<< "$pair"
  code=$(curl -s -o /dev/null -w "%{http_code}" "$url" 2>&1 || echo "000")
  if [ "$code" = "200" ]; then
    echo -e "  ${GREEN}OK${NC}  $name"
    PASS=$((PASS+1))
  else
    echo -e "  ${RED}FAIL${NC} $name ($code)"
    FAIL=$((FAIL+1))
  fi
done

echo ""
echo -e "${BOLD}  URLs:${NC}"
echo -e "  Landing Page:  https://$DOMAIN/"
echo -e "  Buyer App:     https://$DOMAIN/shop/"
echo -e "  Seller:        https://$DOMAIN/seller/"
echo -e "  Admin:         https://$DOMAIN/admin/"
echo -e "  Onboarding:    https://$DOMAIN/admin/onboard"
echo -e "  Pitch:         https://$DOMAIN/pitch"
echo -e "  Registry API:  https://$DOMAIN/registry/health"
echo -e "  Gateway API:   https://$DOMAIN/gateway/health"
echo ""
echo -e "${BOLD}  Credentials:${NC}"
echo -e "  Admin email:    admin@$DOMAIN"
echo -e "  Admin password: $ADMIN_PASSWORD"
echo ""
echo -e "${BOLD}  Commands:${NC}"
echo -e "  pm2 status       — service status"
echo -e "  pm2 logs         — all logs"
echo -e "  pm2 monit        — real-time dashboard"
echo -e "  pm2 restart all  — restart everything"
echo ""
echo -e "  ${PASS} services up, ${FAIL} failed"
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
